# SwiftLint Configuration for netcalc
# Production-quality iOS networking tool

disabled_rules:
  - trailing_whitespace

opt_in_rules:
  - empty_count
  - explicit_init

line_length: 120

# Identifier naming
identifier_name:
  min_length: 2
  max_length: 50

# Type naming
type_name:
  min_length: 3
  max_length: 50

# File length
file_length:
  warning: 500
  error: 1000

# Function length
function_body_length:
  warning: 50
  error: 100

# Type body length
type_body_length:
  warning: 300
  error: 500
